### ISSUE TITLE
Schéam de l'infra

### ISSUE THREAD

**Issue by NicolasGlassey** [CPNV-MON1/Prometheus#13]
Messieurs,

Le seul schéma d'infra surlequel je suis "tombé" est l'officiel produit par Prometheus.
https://prometheus.io/docs/introduction/overview/#architecture

Mais il me semble bien avoir vu en meeting avec Luca, tout comme lors de la démo, un schéma adapté à nos besoins.
Où se cache-t-il ?

Merci !

**Comment by Enelg52** [comment]
@NicolasGlassey 
Le voilà ! https://github.com/CPNV-MON1/Prometheus/wiki/Sch%C3%A9ma
