### ISSUE TITLE
Need modify mail address for using

### ISSUE THREAD

**Issue by LucaBassi** [CPNV-MON1/Prometheus#5]
Confirmation for using CPNV's mail address by AWS not arrived on my mailbox

**Comment by NicolasGlassey** [comment]
@LucaBassi 

I just re-send the activation email with the correct email address.

![image](https://github.com/CPNV-MON1/Prometheus/assets/5616312/c10ed952-0c3c-4b7d-8c86-354b547a47fc)

**Comment by LucaBassi** [comment]
Mail address appouved and service tested - OK
